services:
  # Сервис для ЗАПУСКА ТЕСТОВ
  tests:
    build: .
    ipc: host
    init: true
    volumes:
      - ./allure-results:/app/allure-results
    command: pytest -m "api or ui" --alluredir=allure-results

  # Сервис для ПРОСМОТРА ОТЧЕТА
  allure:
    build: .
    ipc: host
    init: true
    volumes:
      # Этот volume читает результаты
      - ./allure-results:/app/allure-results
      # ЭТОТ VOLUME СОХРАНЯЕТ ГОТОВЫЙ ОТЧЕТ НА ХОСТ
      - ./allure-report:/app/allure-report 
    ports:
      - "5050:5050"
    command: allure serve -h 0.0.0.0 -p 5050 allure-results