name: Run Autotests and Publish Report

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write # Добавляем права для ghcr.io

jobs:
  # ЗАДАНИЕ 1: Сборка и публикация Docker-образа с кэшированием
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Create lower-case image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 5. Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ЗАДАНИЕ 2: Запуск тестов (параллельно) и генерация отчета
  test-and-report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      - name: 2. Create lower-case image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Запускаем API и UI тесты в фоновом режиме, чтобы они шли параллельно
      - name: 3. Run API tests
        run: >
          docker run
          -v $(pwd)/allure-results:/app/allure-results
          -e BASE_URL=${{ secrets.BASE_URL }}
          -e ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
          -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          ${{ env.IMAGE_NAME }}:latest
          pytest -m api --alluredir=allure-results &

      - name: 4. Run UI tests
        run: >
          docker run --ipc=host --init
          -v $(pwd)/allure-results:/app/allure-results
          ${{ env.IMAGE_NAME }}:latest
          pytest -m ui --alluredir=allure-results &

      # Ждем завершения всех фоновых процессов (тестов)
      - name: 5. Wait for all tests to complete
        run: wait

      - name: 6. Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: 7. Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: ./allure-history

  # ЗАДАНИЕ 3: Публикация на GitHub Pages
  deploy:
    needs: test-and-report
    if: always()
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4