name: Run Autotests and Generate Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      - name: 2. Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: 3. Run API and UI tests
        # Убираем 'continue-on-error'. Теперь, если тесты упадут, этот шаг будет КРАСНЫМ.
        run: docker-compose run --rm tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      # Шаг 4: Генерация отчета (БУДЕТ ВЫПОЛНЕН ВСЕГДА)
      - name: 4. Generate static Allure report
        # 'if: always()' гарантирует, что этот шаг запустится, даже если Шаг 3 упал.
        if: always()
        run: docker-compose run --rm allure allure generate allure-results --clean -o allure-report

      # Шаг 5: Выгрузка отчета (БУДЕТ ВЫПОЛНЕН ВСЕГДА)
      - name: 5. Upload Allure Report artifact
        # 'if: always()' здесь был и раньше, и он абсолютно на своем месте.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report