name: Run Autotests and Generate Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Docker Compose
      # Эта команда напрямую скачивает и устанавливает последнюю версию docker-compose.
      - name: 2. Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Шаг 3: Запуск тестов
      # Теперь эта команда точно сработает
      - name: 3. Run API and UI tests
        run: docker-compose run --rm tests

      # Шаг 4: Генерация отчета
      - name: 4. Generate Allure Report
        run: docker run --rm -v $(pwd)/allure-results:/allure-results -v $(pwd)/allure-report:/allure-report smartcosmos/allure-commandline generate /allure-results --clean -o /allure-report

      # Шаг 5: Выгрузка отчета
      - name: 5. Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report