name: Run Autotests and Publish Report with History

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # ЗАДАНИЕ 1: Запуск тестов и подготовка отчета
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      - name: 2. Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: 3. Run API and UI tests
        run: docker-compose run --rm tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      - name: 4. Generate Allure Report with history
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_history: allure-history

      - name: 5. Upload report artifact for deployment
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-history # Загружаем папку, которую подготовил simple-elf
          retention-days: 1

  # ЗАДАНИЕ 2: Публикация отчета на GitHub Pages
  deploy:
    if: always()
    needs: build # Запускается после build
    runs-on: ubuntu-latest
    steps:
      - name: 1. Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report

      - name: 2. Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true # Сохраняем историю