name: Run Autotests and Generate Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      # V-- НОВЫЙ ШАГ ДЛЯ УСТАНОВКИ DOCKER COMPOSE --V
      - name: 2. Set up Docker Compose
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # Шаг 3: Запуск тестов с помощью Docker Compose
      - name: 3. Run API and UI tests
        # Теперь эта команда будет работать, т.к. docker-compose установлен
        run: docker-compose run --rm tests

      # Шаг 4: Генерация Allure-отчета
      - name: 4. Generate Allure Report
        # Этот шаг не меняется
        run: docker run --rm -v $(pwd)/allure-results:/app/allure-results -v $(pwd)/allure-report:/app/allure-report allure/allure-commandline generate /app/allure-results --clean -o /app/allure-report

      # Шаг 5: Выгрузка отчета
      - name: 5. Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report