name: Run Autotests and Generate Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get code from repository
        uses: actions/checkout@v4

      - name: 2. Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: 3. Run API and UI tests
        # 'id' позволяет нам ссылаться на этот шаг позже
        id: run_tests
        continue-on-error: true
        run: docker-compose run --rm tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      - name: 4. Generate static Allure report
        # Этот шаг запускается всегда, благодаря continue-on-error выше
        run: docker-compose run --rm allure allure generate allure-results --clean -o allure-report

      - name: 5. Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report

      # V-- НОВЫЙ ФИНАЛЬНЫЙ ШАГ ПРОВЕРКИ --V
      - name: 6. Check test run status
        # Этот шаг выполняется, только если шаг с id='run_tests' завершился неудачно
        if: steps.run_tests.outcome == 'failure'
        run: |
          echo "Тесты провалились. Проваливаем сборку."
          exit 1